# Generated by Django 5.0.2 on 2024-02-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=200)),
                ('imagess', models.ImageField(upload_to='immdages/')),
                ('brend', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('layer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('pending', 'Jarayonda'), ('confirmed', 'Tasdiqlandi')], default='new', max_length=100)),
            ],
            options={
                'verbose_name': 'Karzinka',
                'verbose_name_plural': 'Karzinkalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differens', models.CharField(max_length=100, verbose_name="O'lcham turi")),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi mahsuloti',
                'verbose_name_plural': 'Foydalanuvchi mahsulotlari',
            },
        ),
    ]
