# Generated by Django 4.2.5 on 2024-03-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='imagess',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
