# Generated by Django 4.2.5 on 2024-03-13 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$')], verbose_name='Telefon raqami')),
            ],
        ),
    ]
