# Generated by Django 4.2.5 on 2024-03-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mynumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyNumbers',
        ),
    ]
